### ISSUE TITLE
[Feature Request] Allow access to other markdown-it options

### ISSUE THREAD

**Issue by washingtonsteven** [tscanlin/processmd#12]
I'd like to tweak some of the markdown process options (namely setting `html:true` to render actual HTML instead of escaping it). It seems like the module is just using `markdown-it`'s default set of options. Would a passthrough be something in scope of what you're trying to do here?

**Comment by tscanlin** [comment]
Yeah, that sounds very useful, thanks for the suggestion. I'll have a PR shortly.

**Comment by tscanlin** [comment]
PR: https://github.com/tscanlin/processmd/pull/13

**Comment by tscanlin** [comment]
I published `4.1.0` with this change.

**Comment by washingtonsteven** [comment]
Thank you!

**Comment by nckhell** [comment]
I'm fairly new to nodeJS (nextjs) dev. How can I set the html to true in the package.json run script?

`processmd content/nieuws/**/**/*.md --outputDir content/nieuws/build --preview 110 --summaryOutput content/nieuws/build/summary.json --markdownOptions ???`

**Comment by washingtonsteven** [comment]
Haven't tried this, but this uses `yargs` to parse arguments. `markdownOptions` is an object, so you should be able to use dot syntax like here: https://github.com/yargs/yargs/blob/master/docs/tricks.md#objects

```
processmd content/nieuws/**/**/*.md --outputDir content/nieuws/build --preview 110 --summaryOutput content/nieuws/build/summary.json --markdownOptions.html true --markdownOptions.linkify true
```
