### ISSUE TITLE
Key of each entries in fileMap object

### ISSUE THREAD

**Issue by nob** [tscanlin/processmd#16]
Thanks for making convenient tool!

In summary.json file, Is it better to use .md file name as key of each entries in fileMap object, rather than .json file name. That way, each entry in the fileMap can be retrieved by items in sourceFileArray directly while looping through the array.
```
{
  "fileMap": {
    "contents/news/json/2018-06-05-cmsからの投稿1.json": {
      "title": "CMSからの投稿1",
      "hilight_days": "4",
      "dir": "contents/news/json",
      "base": "2018-06-05-cmsからの投稿1.json",
      "ext": ".json",
      "sourceBase": "2018-06-05-cmsからの投稿1.md",
      "sourceExt": ".md"
    },
    "contents/news/json/2018-06-05-test2.json": {
      "title": "お知らせ2",
      "hilight_days": "5",
      "dir": "contents/news/json",
      "base": "2018-06-05-test2.json",
      "ext": ".json",
      "sourceBase": "2018-06-05-test2.md",
      "sourceExt": ".md"
    },
    "contents/news/json/2018-04-21-test.json": {
      "title": "お知らせ1",
      "hilight_days": "7",
      "dir": "contents/news/json",
      "base": "2018-04-21-test.json",
      "ext": ".json",
      "sourceBase": "2018-04-21-test.md",
      "sourceExt": ".md"
    }
  },
  "sourceFileArray": [
    "contents/news/2018-04-21-test.md",
    "contents/news/2018-06-05-cmsからの投稿1.md",
    "contents/news/2018-06-05-test2.md"
  ]
}
```
Thank you.

**Comment by tscanlin** [comment]
You can just do ‘Object.keys(data.fileMap)’ to get an array and map over that to get the keys.

Hope that helps!

**Comment by nob** [comment]
OK. I can extract json file name array from fileMap object, but the order of entries in the object is consistent always? 
As you may notice, I am making blog post list page. I'd like to loop through by newest (post) first order.

**Comment by tscanlin** [comment]
The order is the same each time.
