### ISSUE TITLE
[Request] add oprions for preview delimiter

### ISSUE THREAD

**Issue by nshun** [tscanlin/processmd#18]
Japanese use `、` or `。` for sentence delimiter. So plz consider adding options for preview delimiter.

Im changing that line myself now.
https://github.com/tscanlin/processmd/blob/39a9ab26acbc52a6399fcbd80f1ec696849516ac/index.js#L170

**Comment by tscanlin** [comment]
#19 will do just that! Thanks for mentioning here so I can add this feature that will hopefully benefit other international users as well, its very helpful. :)

**Comment by tscanlin** [comment]
`4.4.0` is now published.
