### ISSUE TITLE
Link Open to new tab  

### ISSUE THREAD

**Issue by derit** [tscanlin/processmd#23]
hello, 
i have issue when content have a link, and i click the link but link not opened to new tab, only reload current tab
have solutions?

**Comment by tscanlin** [comment]
This is the default browser behavior. You can add custom code to accomplish
what you want.

**Comment by derit** [comment]
i solved with this document
<https://github.com/markdown-it/markdown-it/blob/master/docs/architecture.md#renderer>

**Comment by tscanlin** [comment]
Glad to hear that!

**Comment by derit** [comment]
i think this can be a feature for options
