### ISSUE TITLE
[Feature] Set the slug in the frontmatter

### ISSUE THREAD

**Issue by bntzio** [tscanlin/processmd#6]
Hi, Tim! 👋

It'd be really awesome if users could specify the `/slug` in the Front Matter of each post 🙂

What do you think?

**Comment by tscanlin** [comment]
You can. That's the beauty of markdown / yaml. However, this project is not concerned with what you do with the json. I think this feature could be useful for next-blog though. Could you open an issue in that repo instead? https://github.com/tscanlin/next-blog

**Comment by bntzio** [comment]
Follow up 👉 https://github.com/tscanlin/next-blog/issues/1
